"""Execute deterministic remediation rules against findings and attack paths."""

from engine.recommendation_rules import RECOMMENDATION_RULES


def analyze_recommendations(findings, attack_paths):
    """Return Recommendation objects generated by the registered rules."""
    recommendations = []

    for rule in RECOMMENDATION_RULES:
        recommendation = rule(findings, attack_paths)

        if recommendation:
            recommendations.append(recommendation)

    return recommendations
