from engine.rules.iam_rules import analyze_iam
from engine.rules.s3_rules import analyze_s3
from engine.rules.ec2_rules import analyze_ec2
from engine.rules.security_group_rules import analyze_security_groups
from engine.rules.cloudtrail_rules import analyze_cloudtrail
from engine.rules.password_policy_rules import analyze_password_policy
from engine.rules.rds_rules import analyze_rds
from engine.rules.vpc_rules import analyze_vpc
from engine.rules.ebs_rules import analyze_ebs
from engine.rules.lambda_rules import analyze_lambda
from engine.rules.ecs_rules import analyze_ecs
from engine.rules.ecr_rules import analyze_ecr
from engine.rules.apigateway_rules import analyze_apigateway
from engine.rules.dynamodb_rules import analyze_dynamodb
from engine.rules.kms_rules import analyze_kms
from engine.rules.secretsmanager_rules import analyze_secretsmanager
from engine.rules.sns_rules import analyze_sns
from engine.rules.sqs_rules import analyze_sqs
from engine.rules.cloudwatch_rules import analyze_cloudwatch
from engine.rules.route53_rules import analyze_route53
from engine.rules.elb_rules import analyze_elb
from engine.rules.autoscaling_rules import analyze_autoscaling
from engine.rules.eip_rules import analyze_eip
from engine.rules.organizations_rules import analyze_organizations