import { useEffect, useState } from "react";
import api from "../services/api";
import { FileText, Download, Calendar, ShieldCheck, Loader2 } from "lucide-react";

function Reports({ selectedAccountId }) {
    const [scans, setScans] = useState([]);
    const [loading, setLoading] = useState(true);

    const loadScans = async () => {
        setLoading(true);
        try {
            const res = await api.get("/scans");
            // Filter completed scans to serve as reports
            const completed = (res.data.scans || []).filter((s) => s.status === "Completed");
            setScans(completed);
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        loadScans();
    }, [selectedAccountId]);

    const handleDownloadPDF = (scanId, accountName) => {
        // Build a simulated PDF download blob
        const reportContent = `--------------------------------------------------
CLOUDINTERCEPT SECURITY REPORT
--------------------------------------------------
Scan Snapshot: #${scanId}
Environment: ${accountName}
Timestamp: ${new Date().toLocaleString()}
Compliance Status: Evaluated

This document certifies that a CloudIntercept security scan was successfully
conducted. All discovered AWS resource assets were verified against active 
security engine rules, correlating attack scenarios, and remediation guidelines.

For full interactive attack progressions and JSON evidence logs, please access the 
CloudIntercept dashboard.

--------------------------------------------------
Generated by CloudIntercept Core Security Advisor.
--------------------------------------------------`;
        
        const blob = new Blob([reportContent], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `CloudIntercept_Report_Scan_${scanId}.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    if (loading) {
        return (
            <div style={{ display: "flex", justifyContent: "center", alignItems: "center", height: "50vh", color: "#64748B" }}>
                <h2>Loading reports catalogue...</h2>
            </div>
        );
    }

    return (
        <div style={{ padding: "30px", color: "#F1F5F9", fontFamily: "Inter, sans-serif" }}>
            <div style={{ marginBottom: "30px" }}>
                <h1 style={{ fontSize: "28px", fontWeight: "700", color: "white", margin: 0 }}>
                    Security Reports
                </h1>
                <p style={{ fontSize: "14px", color: "#94A3B8", marginTop: "4px" }}>
                    Download executive PDF summaries and compliance audit documents for scan snapshots
                </p>
            </div>

            <div style={{ backgroundColor: "#0F172A", border: "1px solid #1E293B", borderRadius: "10px", padding: "25px" }}>
                <h3 style={{ fontSize: "18px", color: "white", margin: "0 0 20px 0", borderBottom: "1px solid #1E293B", paddingBottom: "10px", display: "flex", alignItems: "center", gap: "8px" }}>
                    <FileText size={18} style={{ color: "#38BDF8" }} /> Generated Compliance Reports
                </h3>

                {scans.length === 0 ? (
                    <div style={{ color: "#94A3B8", textAlign: "center", padding: "40px" }}>
                        No completed scan reports available. Initiate a scan to generate compliance files.
                    </div>
                ) : (
                    <div style={{ display: "flex", flexDirection: "column", gap: "15px" }}>
                        {scans.map((s) => (
                            <div key={s.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", backgroundColor: "#1E293B", border: "1px solid #334155", padding: "16px 20px", borderRadius: "8px" }}>
                                <div style={{ display: "flex", alignItems: "center", gap: "15px" }}>
                                    <div style={{ padding: "10px", borderRadius: "8px", backgroundColor: "#0C4A6E", color: "#38BDF8" }}>
                                        <FileText size={20} />
                                    </div>
                                    <div>
                                        <h4 style={{ fontSize: "15px", color: "white", margin: "0 0 4px 0", fontWeight: "600" }}>
                                            CloudIntercept Compliance Report - Scan #{s.id}
                                        </h4>
                                        <div style={{ display: "flex", gap: "15px", fontSize: "12px", color: "#94A3B8" }}>
                                            <span style={{ display: "inline-flex", alignItems: "center", gap: "4px" }}>
                                                <Calendar size={12} />
                                                {new Date(s.started_at).toLocaleString()}
                                            </span>
                                            <span>
                                                Environment: <strong>{s.account_name}</strong>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <button
                                    onClick={() => handleDownloadPDF(s.id, s.account_name)}
                                    style={{
                                        display: "flex",
                                        alignItems: "center",
                                        gap: "8px",
                                        padding: "8px 16px",
                                        backgroundColor: "#0F172A",
                                        color: "#38BDF8",
                                        border: "1px solid #334155",
                                        borderRadius: "6px",
                                        cursor: "pointer",
                                        fontSize: "13px",
                                        fontWeight: "600",
                                        transition: "all 0.2s"
                                    }}
                                    onMouseEnter={(e) => e.currentTarget.style.backgroundColor = "#1E293B"}
                                    onMouseLeave={(e) => e.currentTarget.style.backgroundColor = "#0F172A"}
                                >
                                    <Download size={14} /> Download PDF
                                </button>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}

export default Reports;
